export default {
  'A Mighty Fortress is Our God': [],
  'All Glory, Laud and Honor': [],
  'All Hail the Power of Jesus’ Name': [],
  'America the Beautiful': [],
  'Amazing Grace': [],
  'And Can It Be': [],
  'Angels We Have Heard on High': [],
  'Angels, from the Realms of Glory': [],
  'As with Gladness Men of Old': [],
  'At Calvary': [],
  'At the Cross': [],
  'Away in a Manger': [],
  'Battle Hymn of the Republic': [],
  'Blest Be the Tie That Binds': [],
  'Brethren, We Have Met to Worship': [],
  'Children of the Heavenly Father': [],
  'Christ Arose!': [],
  'Christ the Lord Is Risen Today': [],
  'Come, Thou Fount of Every Blessing': [],
  'Crown Him with Many Crowns': [],
  'Face to Face': [],
  'Fairest Lord Jesus': [],
  'For the Beauty of the Earth': [],
  'Go to Dark Gethsemane': [],
  'God of Our Fathers': [],
  'God Rest Ye Merry, Gentlemen': [],
  'Good Christian Men, Rejoice': [],
  'Grace Greater than Our Sin': [],
  'Hallelujah, What a Savior!': [],
  'Hark! the Herald Angels Sing': [],
  'Have Thine Own Way, Lord!': [],
  'Higher Ground': [],
  'Holy Holy Holy': [],
  'How Firm A Foundation': [],
  'How Great Our Joy': [],
  'I Heard the Bells on Christmas Day': [],
  'I Sing the Mighty Power of God': [],
  'I Surrender All': [],
  'In the Garden': [],
  'It Came upon the Midnight Clear': [],
  'It Is Well with My Soul': [],
  'Jesus Paid it All': [],
  'Joy to the World!': [],
  'Joyful, Joyful, We Adore Thee': [],
  'Just As I Am': [],
  'Leaning on the Everlasting Arms': [],
  'My Country, ‘Tis of Thee': [],
  'Nothing But the Blood': [],
  'O Come, All Ye Faithful': [],
  'O Come, O Come, Emmanuel': [],
  'O for a Thousand Tongues to Sing': [],
  'O Holy Night': [],
  'O Little Town of Bethlehem': [],
  'O Sacred Head, Now Wounded': [],
  'Praise Him! Praise Him!': [],
  'Praise to the Lord, the Almighty': [],
  'Rock of Ages': [],
  'Shall We Gather at the River?': [],
  'Silent Night! Holy Night!': [],
  'Standing on the Promises': [],
  'Take My Life and Let It Be': [],
  'The First Noel': [],
  'The Lord Bless You and Keep You': [],
  'The Old Rugged Cross': [],
  'The Solid Rock': [],
  'There Is a Fountain': [],
  'This Is my Father’s World': [],
  'To God Be the Glory': [],
  'We Three Kings': [],
  'Were You There?': [],
  'What Child Is This?': [],
  'When I Survey the Wondrous Cross': [],
  'While Shepherds Watched Their Flocks': [],
  'Wonderful Grace of Jesus': [],
}
